include:
  - data-services/mysql.yml
  - data-services/redis.yml
  - data-services/opensearch.yml
  - data-services/kafka.yml
  - core-services/core-app1.yml
  - core-services/core-app2.yml
  - dip-services/dip-app1.yml
  - dip-services/dip-app2.yml
  - router-services/router-app.yml

services:
  gateway:
    image: caddy:alpine
    ports:
      - "80:80"
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile

configs:
  caddyfile:
    file: ./Caddyfile
