events {}

http {
  resolver 127.0.0.11 valid=10s ipv6=off;

  server {
    listen 80;
    server_name _;

    location = / {
      default_type text/plain;
      return 200 'available services:
/core-services/core-app1/
/core-services/core-app2/
/dip-services/dip-app1/
/dip-services/dip-app2/
';
    }

    location = /core-services/core-app1 {
      return 301 /core-services/core-app1/;
    }

    location /core-services/core-app1/ {
      set $upstream http://core-app1:80/;
      proxy_pass $upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /core-services/core-app2 {
      return 301 /core-services/core-app2/;
    }

    location /core-services/core-app2/ {
      set $upstream http://core-app2:80/;
      proxy_pass $upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /dip-services/dip-app1 {
      return 301 /dip-services/dip-app1/;
    }

    location /dip-services/dip-app1/ {
      set $upstream http://dip-app1:80/;
      proxy_pass $upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /dip-services/dip-app2 {
      return 301 /dip-services/dip-app2/;
    }

    location /dip-services/dip-app2/ {
      set $upstream http://dip-app2:80/;
      proxy_pass $upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
